# Tensors

- Specialized data structures similar to arrays and matrices.
- These Encode inputs, outputs, and model parameters in PyTorch.
- They Resemble NumPy's ndarrays but with additional GPU and hardware acceleration support.
- Can share memory with NumPy arrays, reducing data duplication.
- Optimized for automatic differentiation, essential for gradient-based learning in deep learning algorithms.

In [2]:
import torch
import numpy as np

# Initializing a Tensor
### 1. From Data 

In [9]:
data = [[1,2], [3,4]]
data

[[1, 2], [3, 4]]

In [10]:
tensor_data = torch.tensor(data)
tensor_data

tensor([[1, 2],
        [3, 4]])

### 2. From a NumPy array

In [8]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [13]:
tensor_array = torch.tensor(np_array)
tensor_array

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [14]:
tensor_array2 = torch.from_numpy(np_array)
tensor_array2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**Note: tensor from numpy has has data type of element as well.**

### 3. From another tensor
- **ones_like**
- **rand_like**

In [15]:
x_ones = torch.ones_like(tensor_data)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [20]:
x_rand = torch.rand_like(tensor_data, dtype=torch.float32)
x_rand

tensor([[0.0950, 0.9127],
        [0.7641, 0.9433]])

### 4. With Shape

In [24]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5986, 0.8283, 0.5263],
        [0.5656, 0.4118, 0.6181]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

In [26]:
tensor = torch.rand((2,3))
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operation in tensors

In [29]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

The line **tensor = tensor.to("cuda")** in PyTorch moves the PyTorch tensor named **tensor** onto a CUDA-enabled GPU for faster computations if a compatible GPU is available.

### 1. indexing and slicing

In [49]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[1]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 2. joining tensors

In [87]:
join_tensor = torch.cat([tensor, tensor, tensor], dim=1) # dim=1 -> along col; dim=2 -> along row
print(join_tensor)

tensor([[6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.]])


### 3. Arithmetic Operation 

In [84]:
data_1 = [[1,2,3],[4,5,6]]
data_2 = [[10,11],[12,13],[5,6]]
tensor_1 = torch.tensor(data_1)
tensor_2 = torch.tensor(data_2)

pre_mul = tensor_1 @ tensor_2
post_mul = tensor_2 @ tensor_1

In [59]:
pre_mul

tensor([[ 49,  55],
        [130, 145]])

In [60]:
post_mul

tensor([[ 54,  75,  96],
        [ 64,  89, 114],
        [ 29,  40,  51]])

In [64]:
post_mult = torch.matmul(tensor_1, tensor_2)
post_mult

tensor([[ 49,  55],
        [130, 145]])

In [69]:
z1 = tensor_1*tensor_1
z1

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [71]:
z2 = torch.mul(tensor_1, tensor_1)
z2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

### 4. Single-element tensors
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using **.item():**

In [86]:
tensor_1

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [74]:
agg = tensor_1.sum()
agg

tensor(21)

In [75]:
agg_item = agg.item()
print(agg_item, type(agg_item))

21 <class 'int'>


###  5. Inplace operation

In PyTorch, certain operations modify the original variable directly, storing the result within the same variable. These are referred to as in-place operations and are indicated by a suffix `_`.

For example:

- `x.copy_(y)`: This function copies the contents of tensor `y` into tensor `x`, altering `x` directly.
- `x.t_()`: Transposes tensor `x` and saves the transposed result back into the original variable `x`.

These in-place operations directly change the original tensor without creating a new one or requiring reassignment. While they can save memory by avoiding unnecessary tensor copies, they might make code harder to debug as they modify tensors destructively.


In [85]:
print(tensor_1, '\n')
tensor_1.add_(5)
print(tensor_1)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


**NOTE:**
    In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

### 6. Bridge with NumPy

#### tensor to Numpy array

In [94]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [95]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [96]:
t.add_(10)
print("Tensor:", t)
print("numpy:", n)

Tensor: tensor([11., 11., 11., 11., 11.])
numpy: [11. 11. 11. 11. 11.]


#### Numpy array to tensor

In [105]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [106]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [111]:
np.add(n, 10, out = n)
print(n)
print(t)

[32. 32. 32. 32. 32.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
