$$\textbf{Day 1}$$

---
---

In [1]:
import numpy as np

### Create Basic Arrays

1. Create a 1D NumPy array of 10 zeros.

In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5)) # put tuple inside it

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2. Create an array of 10 fives

In [ ]:
np.ones(shape=(10), dtype=int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.full((10), 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

3. Create a 1D array of integers from 10 to 50

In [ ]:
np.arange(start=10, stop=51, dtype=int, device = 'cpu')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Array Properties

4. Create a 3×3 array of random integers between 1 and 10.

In [ ]:
np.random.random(size=(3,3))*10

array([[9.47707174, 2.88534895, 3.31737704],
       [0.08426638, 5.25223678, 0.5827369 ],
       [2.51429348, 7.011908  , 7.04900207]])

This can be less than one as well. Let's try something else.

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Not random.

In [ ]:
np.random.uniform(1, 10, (3,3))

array([[5.9826283 , 2.75650014, 2.26468861],
       [1.31295921, 7.3824902 , 9.81033485],
       [1.66865601, 8.27303223, 9.6417458 ]])

5. Print its shape, size, number of dimensions, and data type.

In [ ]:
a = np.random.uniform(1, 10, (3,3))
a.shape

(3, 3)

In [ ]:
a.size

9

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.ravel()

array([1.91530435, 3.67255281, 8.83155749, 7.90251324, 1.48335617,
       9.55944709, 5.36692331, 2.25734379, 7.63001007])

# Reshape and Indexing

6. Reshape a 1D array of 25 elements into a 5×5 matrix.



In [ ]:
np.random.random(25).reshape((5,5))

array([[0.8673698 , 0.42001303, 0.8857146 , 0.35954082, 0.40694807],
       [0.77054625, 0.15249678, 0.66212568, 0.66989244, 0.9587944 ],
       [0.89819065, 0.78833591, 0.96059348, 0.33447257, 0.42597176],
       [0.91507869, 0.47439715, 0.4737502 , 0.55710872, 0.17330271],
       [0.07767138, 0.89970487, 0.61155724, 0.52470293, 0.49446355]])

7. Extract the 2nd row.





In [ ]:
b = np.random.random(25).reshape((5,5))
b

array([[0.56145061, 0.02211646, 0.24853587, 0.61223716, 0.06407304],
       [0.24675824, 0.6422091 , 0.96495898, 0.06160861, 0.73347973],
       [0.90437584, 0.42356512, 0.97737584, 0.13348148, 0.45351745],
       [0.56861258, 0.93292308, 0.70804849, 0.88580585, 0.73356387],
       [0.1620257 , 0.66778998, 0.17949926, 0.8436474 , 0.69547389]])

In [ ]:
b[1]

array([0.24675824, 0.6422091 , 0.96495898, 0.06160861, 0.73347973])

8. Extract the last column.

In [ ]:
b[:, -1]

array([0.06407304, 0.73347973, 0.45351745, 0.73356387, 0.69547389])

9. Reverse the rows.

In [ ]:
b[::-1]

array([[0.1620257 , 0.66778998, 0.17949926, 0.8436474 , 0.69547389],
       [0.56861258, 0.93292308, 0.70804849, 0.88580585, 0.73356387],
       [0.90437584, 0.42356512, 0.97737584, 0.13348148, 0.45351745],
       [0.24675824, 0.6422091 , 0.96495898, 0.06160861, 0.73347973],
       [0.56145061, 0.02211646, 0.24853587, 0.61223716, 0.06407304]])

10. Given a 5×5 matrix of values from 1 to 25, extract a 3×3 sub-matrix from the center.



In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.arange(25).reshape(5,5)[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

11. From a random array of integers between 0 and 100, filter all values > 50.

In [ ]:
c = np.random.randint(1,100, (5,5))
c

array([[ 9, 87, 17, 26, 41],
       [81, 87, 38, 78,  6],
       [ 2, 77,  2, 65, 66],
       [49,  6, 64, 49, 73],
       [13, 76, 43, 68, 23]])

In [ ]:
c[c>50]

array([87, 81, 87, 78, 77, 65, 66, 64, 73, 76, 68])

12. Create a 3x3 matrix with all values 1, then add a vector [1, 2, 3] to each row.

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3)) + np.array([1,2,3])

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [ ]:
np.ones((3,3)) + np.array([1,2,3]).reshape(3, 1)

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3]).reshape(3, 1)

array([[1],
       [2],
       [3]])

13. Create two random 3×3 matrices and perform:

- Element-wise addition

- Matrix multiplication

- Element-wise division


In [ ]:
a = np.random.randint(1, 10, (3,3))
b = np.random.randint(1, 10, (3,3))

In [ ]:
a

array([[4, 6, 5],
       [1, 8, 9],
       [4, 1, 1]])

In [ ]:
b

array([[9, 8, 7],
       [6, 6, 8],
       [2, 3, 8]])

In [ ]:
a+b

array([[13, 14, 12],
       [ 7, 14, 17],
       [ 6,  4,  9]])

In [ ]:
a*b

array([[36, 48, 35],
       [ 6, 48, 72],
       [ 8,  3,  8]])

In [ ]:
b/a

array([[2.25      , 1.33333333, 1.4       ],
       [6.        , 0.75      , 0.88888889],
       [0.5       , 3.        , 8.        ]])

In [ ]:
a/b

array([[0.44444444, 0.75      , 0.71428571],
       [0.16666667, 1.33333333, 1.125     ],
       [2.        , 0.33333333, 0.125     ]])

14. Given a 5×4 matrix of random values, calculate:

- Mean of each column

- Standard deviation of each row

- Find the index of the max element

In [ ]:
d = np.random.randint(1,10, (5,4))
d

array([[2, 3, 6, 8],
       [8, 3, 6, 8],
       [2, 7, 9, 5],
       [7, 9, 9, 7],
       [8, 2, 4, 9]])

In [ ]:
d.mean(axis=0) # axis = 0 -> sum across cols

array([5.4, 4.8, 6.8, 7.4])

In [ ]:
d.mean(axis=1) # axis = 1 -> sum across rows

array([4.75, 6.25, 5.75, 8.  , 5.75])

In [ ]:
d.std(axis=1)

array([2.384848  , 2.04633819, 2.58602011, 1.        , 2.86138079])

In [ ]:
np.max(d)

np.int64(9)

In [ ]:
np.argmax(d)

np.int64(10)

$$\textbf{Day 2}$$

---

In [1]:
import numpy as np

1. Create an array of shape (3, 4) filled with integers from 0 to 11 using a single line of NumPy code. Then, flatten it using a method that does not create a copy

In [2]:
a = np.random.randint(1, 12, (3, 4))